// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzouimhrfkxreydigqsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6b3VpbWhyZmt4cmV5ZGlncXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTAzNzIsImV4cCI6MjA3MzQyNjM3Mn0.ofNupjSG7MLwtxkUOuDMI3r0_016NW5fmGLU4TY9Xdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});